#!/usr/bin/env python
from __future__ import print_function
import re
import sys


def ferror(fname, line, msg):
    return print("%s:%s:" % (fname, line), msg, file=sys.stderr)


def parse_style(fname):
    status = 0
    with open(fname, "rU") as f:
        for i, line in enumerate(f, 1):
            if len(line) >= 80:
                ferror(fname, i, "line over 80 colums")
                status |= 1
            if " " in line and "\t" in line:
                ferror(fname, i, "mixed tabs and spaces")
                status |= 1
            if re.match("[ \t\r]+$", line):
                ferror(fname, i, "trailing whitespace")
                status |= 1
    return status


def main():
    status = 0
    for fname in sys.argv[1:]:
        status |= parse_style(fname)
    sys.exit(status)


if __name__ == "__main__":
    main()
